"""initial schema

Revision ID: d19ff42ba5ac
Revises: 
Create Date: 2026-09-16 10:36:54.281899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd19ff42ba5ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations_provinces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('shareholder_module_enabled', sa.Boolean(), nullable=False),
    sa.Column('primary_color', sa.String(length=16), nullable=False),
    sa.Column('secondary_color', sa.String(length=16), nullable=False),
    sa.Column('primary_light_color', sa.String(length=16), nullable=False),
    sa.Column('font_family', sa.String(length=64), nullable=False),
    sa.Column('logo_file', sa.String(length=512), nullable=True),
    sa.Column('favicon_file', sa.String(length=512), nullable=True),
    sa.Column('default_og_image_file', sa.String(length=512), nullable=True),
    sa.Column('footer_text', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'tenant_admin', name='adminrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(role = 'super_admin' AND tenant_id IS NULL) OR (role = 'tenant_admin' AND tenant_id IS NOT NULL)", name='ck_admin_users_role_tenant'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_index(op.f('ix_admin_users_tenant_id'), 'admin_users', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('citizenship_file', sa.String(length=512), nullable=True),
    sa.Column('bank_deposit_file', sa.String(length=512), nullable=True),
    sa.Column('request_form_file', sa.String(length=512), nullable=True),
    sa.Column('share_type', sa.String(length=64), nullable=True),
    sa.Column('pan', sa.String(length=64), nullable=True),
    sa.Column('nid', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='applicationstatus'), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_tenant_id'), 'applications', ['tenant_id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('file', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_tenant_id'), 'contacts', ['tenant_id'], unique=False)
    op.create_table('content_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('group', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('file', sa.String(length=512), nullable=True),
    sa.Column('infos', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'key', name='uq_content_settings_tenant_key')
    )
    op.create_index(op.f('ix_content_settings_group'), 'content_settings', ['group'], unique=False)
    op.create_index(op.f('ix_content_settings_tenant_id'), 'content_settings', ['tenant_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('file', sa.String(length=512), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_tenant_id'), 'documents', ['tenant_id'], unique=False)
    op.create_table('galleries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_galleries_tenant_id'), 'galleries', ['tenant_id'], unique=False)
    op.create_table('locations_districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['province_id'], ['locations_provinces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_districts_province_id'), 'locations_districts', ['province_id'], unique=False)
    op.create_table('nav_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.Enum('header', 'footer', name='navlocation'), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_external', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['nav_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nav_items_tenant_id'), 'nav_items', ['tenant_id'], unique=False)
    op.create_table('popups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=512), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_popups_tenant_id'), 'popups', ['tenant_id'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('file', sa.String(length=512), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_tenant_id'), 'portfolios', ['tenant_id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('image', sa.String(length=512), nullable=True),
    sa.Column('additional_info', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_tenant_id'), 'teams', ['tenant_id'], unique=False)
    op.create_table('tenant_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname', name='uq_tenant_domains_hostname')
    )
    op.create_index(op.f('ix_tenant_domains_hostname'), 'tenant_domains', ['hostname'], unique=False)
    op.create_index(op.f('ix_tenant_domains_tenant_id'), 'tenant_domains', ['tenant_id'], unique=False)
    op.create_table('gallery_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gallery_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('file', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['gallery_id'], ['galleries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_images_gallery_id'), 'gallery_images', ['gallery_id'], unique=False)
    op.create_table('locations_municipalities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['locations_districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_municipalities_district_id'), 'locations_municipalities', ['district_id'], unique=False)
    op.create_table('shareholders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=64), nullable=True),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('name_np', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('mobile', sa.String(length=32), nullable=True),
    sa.Column('pan', sa.String(length=64), nullable=True),
    sa.Column('father_name', sa.String(length=255), nullable=True),
    sa.Column('grandfather_name', sa.String(length=255), nullable=True),
    sa.Column('spouse_name', sa.String(length=255), nullable=True),
    sa.Column('shareholder_number', sa.String(length=64), nullable=True),
    sa.Column('share_certificate_number', sa.String(length=64), nullable=True),
    sa.Column('share_photo', sa.String(length=512), nullable=True),
    sa.Column('share_signature', sa.String(length=512), nullable=True),
    sa.Column('agency', sa.String(length=255), nullable=True),
    sa.Column('share_number', sa.String(length=64), nullable=True),
    sa.Column('share_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shareholders_tenant_id'), 'shareholders', ['tenant_id'], unique=False)
    op.create_table('shareholder_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shareholder_id', sa.Integer(), nullable=False),
    sa.Column('address_type', sa.Enum('permanent', 'contact', name='addresstype'), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('municipality_id', sa.Integer(), nullable=True),
    sa.Column('ward', sa.String(length=16), nullable=True),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['locations_districts.id'], ),
    sa.ForeignKeyConstraint(['municipality_id'], ['locations_municipalities.id'], ),
    sa.ForeignKeyConstraint(['province_id'], ['locations_provinces.id'], ),
    sa.ForeignKeyConstraint(['shareholder_id'], ['shareholders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shareholder_addresses_shareholder_id'), 'shareholder_addresses', ['shareholder_id'], unique=False)
    op.create_table('shareholder_bank_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shareholder_id', sa.Integer(), nullable=False),
    sa.Column('demat_number', sa.String(length=64), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('branch_name', sa.String(length=255), nullable=True),
    sa.Column('account_number', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['shareholder_id'], ['shareholders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shareholder_id')
    )
    op.create_table('shareholder_citizenship_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shareholder_id', sa.Integer(), nullable=False),
    sa.Column('citizenship_number', sa.String(length=64), nullable=True),
    sa.Column('issued_district', sa.String(length=128), nullable=True),
    sa.Column('issued_date', sa.String(length=32), nullable=True),
    sa.Column('file', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['shareholder_id'], ['shareholders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shareholder_id')
    )
    op.create_table('shareholder_national_id_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shareholder_id', sa.Integer(), nullable=False),
    sa.Column('national_id_number', sa.String(length=64), nullable=True),
    sa.Column('file', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['shareholder_id'], ['shareholders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shareholder_id')
    )
    op.create_table('shareholder_nominees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shareholder_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('relation', sa.String(length=128), nullable=True),
    sa.Column('citizenship_number', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['shareholder_id'], ['shareholders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shareholder_nominees_shareholder_id'), 'shareholder_nominees', ['shareholder_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shareholder_nominees_shareholder_id'), table_name='shareholder_nominees')
    op.drop_table('shareholder_nominees')
    op.drop_table('shareholder_national_id_info')
    op.drop_table('shareholder_citizenship_info')
    op.drop_table('shareholder_bank_info')
    op.drop_index(op.f('ix_shareholder_addresses_shareholder_id'), table_name='shareholder_addresses')
    op.drop_table('shareholder_addresses')
    op.drop_index(op.f('ix_shareholders_tenant_id'), table_name='shareholders')
    op.drop_table('shareholders')
    op.drop_index(op.f('ix_locations_municipalities_district_id'), table_name='locations_municipalities')
    op.drop_table('locations_municipalities')
    op.drop_index(op.f('ix_gallery_images_gallery_id'), table_name='gallery_images')
    op.drop_table('gallery_images')
    op.drop_index(op.f('ix_tenant_domains_tenant_id'), table_name='tenant_domains')
    op.drop_index(op.f('ix_tenant_domains_hostname'), table_name='tenant_domains')
    op.drop_table('tenant_domains')
    op.drop_index(op.f('ix_teams_tenant_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_portfolios_tenant_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_popups_tenant_id'), table_name='popups')
    op.drop_table('popups')
    op.drop_index(op.f('ix_nav_items_tenant_id'), table_name='nav_items')
    op.drop_table('nav_items')
    op.drop_index(op.f('ix_locations_districts_province_id'), table_name='locations_districts')
    op.drop_table('locations_districts')
    op.drop_index(op.f('ix_galleries_tenant_id'), table_name='galleries')
    op.drop_table('galleries')
    op.drop_index(op.f('ix_documents_tenant_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_content_settings_tenant_id'), table_name='content_settings')
    op.drop_index(op.f('ix_content_settings_group'), table_name='content_settings')
    op.drop_table('content_settings')
    op.drop_index(op.f('ix_contacts_tenant_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_applications_tenant_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_tenant_id'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_table('locations_provinces')
    # ### end Alembic commands ###
